# Generated by Django 4.2.1 on 2023-06-24 08:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hris_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='miscellaneousinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('third_degree', models.CharField(blank=True, max_length=99, null=True, verbose_name='third_degree')),
                ('third_degree_specify', models.CharField(blank=True, max_length=99, null=True, verbose_name='third_degree_specify')),
                ('fourth_degree', models.CharField(blank=True, max_length=99, null=True, verbose_name='fourth_degree')),
                ('fourth_degree_specify', models.CharField(blank=True, max_length=99, null=True, verbose_name='fourth_degree_specify')),
                ('guilty', models.CharField(blank=True, max_length=99, null=True, verbose_name='guilty')),
                ('guilty_specify', models.CharField(blank=True, max_length=99, null=True, verbose_name='guilty_specify')),
                ('criminally', models.CharField(blank=True, max_length=99, null=True, verbose_name='criminally')),
                ('criminally_specify', models.CharField(blank=True, max_length=99, null=True, verbose_name='criminally_specify')),
                ('date', models.DateField(blank=True, null=True, verbose_name='date')),
                ('convicted', models.CharField(blank=True, max_length=99, null=True, verbose_name='convicted')),
                ('convicted_specify', models.CharField(blank=True, max_length=99, null=True, verbose_name='convicted_specify')),
                ('separated_service', models.CharField(blank=True, max_length=99, null=True, verbose_name='separated_service')),
                ('separated_service_specify', models.CharField(blank=True, max_length=99, null=True, verbose_name='separated_service_specify')),
                ('candidate', models.CharField(blank=True, max_length=99, null=True, verbose_name='candidate')),
                ('candidate_specify', models.CharField(blank=True, max_length=99, null=True, verbose_name='candidate_specify')),
                ('resigned', models.CharField(blank=True, max_length=99, null=True, verbose_name='resigned')),
                ('resigned_specify', models.CharField(blank=True, max_length=99, null=True, verbose_name='resigned_specify')),
                ('immigrant', models.CharField(blank=True, max_length=99, null=True, verbose_name='immigrant')),
                ('immigrant_specify', models.CharField(blank=True, max_length=99, null=True, verbose_name='immigrant_specify')),
                ('indigenous', models.CharField(blank=True, max_length=99, null=True, verbose_name='indigenous')),
                ('indig_specify', models.CharField(blank=True, max_length=99, null=True, verbose_name='indig_specify')),
                ('disability', models.CharField(blank=True, max_length=99, null=True, verbose_name='disability')),
                ('disab_specify', models.CharField(blank=True, max_length=99, null=True, verbose_name='disab_specify')),
                ('solo_parent', models.CharField(blank=True, max_length=99, null=True, verbose_name='solo_parent')),
                ('solo_specify', models.CharField(blank=True, max_length=99, null=True, verbose_name='solo_specify')),
                ('authUser', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='authUser')),
            ],
        ),
        migrations.RemoveField(
            model_name='references',
            name='disab_specify',
        ),
        migrations.RemoveField(
            model_name='references',
            name='disability',
        ),
        migrations.RemoveField(
            model_name='references',
            name='indig_specify',
        ),
        migrations.RemoveField(
            model_name='references',
            name='indigenous',
        ),
        migrations.RemoveField(
            model_name='references',
            name='solo_parent',
        ),
        migrations.RemoveField(
            model_name='references',
            name='solo_specify',
        ),
        migrations.AddField(
            model_name='family_background',
            name='child1',
            field=models.CharField(blank=True, max_length=99, null=True, verbose_name='child1'),
        ),
        migrations.AddField(
            model_name='family_background',
            name='child10',
            field=models.CharField(blank=True, max_length=99, null=True, verbose_name='child10'),
        ),
        migrations.AddField(
            model_name='family_background',
            name='child2',
            field=models.CharField(blank=True, max_length=99, null=True, verbose_name='child2'),
        ),
        migrations.AddField(
            model_name='family_background',
            name='child3',
            field=models.CharField(blank=True, max_length=99, null=True, verbose_name='child3'),
        ),
        migrations.AddField(
            model_name='family_background',
            name='child4',
            field=models.CharField(blank=True, max_length=99, null=True, verbose_name='child4'),
        ),
        migrations.AddField(
            model_name='family_background',
            name='child5',
            field=models.CharField(blank=True, max_length=99, null=True, verbose_name='child5'),
        ),
        migrations.AddField(
            model_name='family_background',
            name='child6',
            field=models.CharField(blank=True, max_length=99, null=True, verbose_name='child6'),
        ),
        migrations.AddField(
            model_name='family_background',
            name='child7',
            field=models.CharField(blank=True, max_length=99, null=True, verbose_name='child7'),
        ),
        migrations.AddField(
            model_name='family_background',
            name='child8',
            field=models.CharField(blank=True, max_length=99, null=True, verbose_name='child8'),
        ),
        migrations.AddField(
            model_name='family_background',
            name='child9',
            field=models.CharField(blank=True, max_length=99, null=True, verbose_name='child9'),
        ),
        migrations.AddField(
            model_name='family_background',
            name='date_birth1',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='date_birth1'),
        ),
        migrations.AddField(
            model_name='family_background',
            name='date_birth10',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='date_birth10'),
        ),
        migrations.AddField(
            model_name='family_background',
            name='date_birth2',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='date_birth2'),
        ),
        migrations.AddField(
            model_name='family_background',
            name='date_birth3',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='date_birth3'),
        ),
        migrations.AddField(
            model_name='family_background',
            name='date_birth4',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='date_birth4'),
        ),
        migrations.AddField(
            model_name='family_background',
            name='date_birth5',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='date_birth5'),
        ),
        migrations.AddField(
            model_name='family_background',
            name='date_birth6',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='date_birth6'),
        ),
        migrations.AddField(
            model_name='family_background',
            name='date_birth7',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='date_birth7'),
        ),
        migrations.AddField(
            model_name='family_background',
            name='date_birth8',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='date_birth8'),
        ),
        migrations.AddField(
            model_name='family_background',
            name='date_birth9',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='date_birth9'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='image',
            field=models.ImageField(blank=True, default='None', null=True, upload_to='image/'),
        ),
        migrations.DeleteModel(
            name='children',
        ),
    ]
