# Generated by Django 4.2.1 on 2023-06-24 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hris_app', '0002_miscellaneousinfo_remove_references_disab_specify_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_information',
            name='name_ext',
            field=models.CharField(blank=True, default='', max_length=99, null=True, verbose_name='name_ext'),
        ),
    ]
