# Generated by Django 4.2.1 on 2023-06-26 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hris_app', '0003_alter_personal_information_name_ext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
    ]
