from django.db import models
from django.contrib.auth import get_user_model
from django.contrib.auth.models import User
User = get_user_model()

class personal(models.Model):
    authUser = models.OneToOneField(User, on_delete=models.CASCADE, verbose_name='authUser')
    division = models.CharField(verbose_name='division', max_length=99)
    unit = models.CharField(verbose_name='unit', max_length=99)
    status = models.CharField(verbose_name='status', max_length=99,blank=True, default='Activated')
    image = models.ImageField(upload_to="image/", blank=True,null=True)

class personal_information(models.Model):
    authUser = models.OneToOneField(User, on_delete=models.CASCADE, verbose_name='authUser', blank=True,null=True)
    name_ext = models.CharField(verbose_name='name_ext', max_length=99, default="", blank=True,null=True)
    surname = models.CharField(verbose_name='surname', max_length=99, blank=True,null=True)
    firstname= models.CharField(verbose_name='firstname', max_length=99, blank=True,null=True)
    middlename = models.CharField(verbose_name='middlename', max_length=99, blank=True,null=True)
    date_of_birth = models.DateField(verbose_name='date_of_birth', blank=True,null=True)
    place_of_birth = models.CharField(verbose_name='place_of_birth', max_length=99, blank=True,null=True)
    sex = models.CharField(verbose_name='sex', max_length=99, blank=True,null=True)
    citizenship = models.CharField(verbose_name='citizenship', max_length=99, blank=True,null=True)
    civil_status = models.CharField(verbose_name='civil_status', max_length=99, blank=True,null=True)
    bloodtype = models.CharField(verbose_name='bloodtype', max_length=99, blank=True,null=True)
    height = models.CharField(verbose_name='height', max_length=99, blank=True,null=True)
    weight = models.CharField(verbose_name='weight', max_length=99, blank=True,null=True)
    gsis = models.CharField(verbose_name='gsis', max_length=99, blank=True,null=True)
    agency_no = models.CharField(verbose_name='agency_no', max_length=99, blank=True,null=True)
    pagibig = models.CharField(verbose_name='pagibig', max_length=99, blank=True,null=True)
    philhealth = models.CharField(verbose_name='philhealth', max_length=99, blank=True,null=True)
    sss = models.CharField(verbose_name='sss', max_length=99, blank=True,null=True)
    tin = models.CharField(verbose_name='tin', max_length=99, blank=True,null=True)
    telno = models.CharField(verbose_name='telno', max_length=99, blank=True,null=True)
    mobile = models.CharField(verbose_name='mobile', max_length=99, blank=True,null=True)
    email = models.EmailField(verbose_name='email', max_length=99, blank=True,null=True)

    res_block = models.CharField(verbose_name='res_block', max_length=99, blank=True,null=True)
    res_street = models.CharField(verbose_name='res_street', max_length=99, blank=True,null=True)
    res_subd = models.CharField(verbose_name='res_subd', max_length=99, blank=True,null=True)
    res_brgy = models.CharField(verbose_name='res_brgy', max_length=99, blank=True,null=True)
    res_city = models.CharField(verbose_name='res_city', max_length=99, blank=True,null=True)
    res_prov = models.CharField(verbose_name='res_prov', max_length=99, blank=True,null=True)
    res_zip = models.CharField(verbose_name='res_zip', max_length=99, blank=True,null=True)

    per_block = models.CharField(verbose_name='per_block', max_length=99, blank=True,null=True)
    per_street = models.CharField(verbose_name='per_street', max_length=99, blank=True,null=True)
    per_subd = models.CharField(verbose_name='per_subd', max_length=99, blank=True,null=True)
    per_brgy = models.CharField(verbose_name='per_brgy', max_length=99, blank=True,null=True)
    per_city = models.CharField(verbose_name='per_city', max_length=99, blank=True,null=True)
    per_prov = models.CharField(verbose_name='per_prov', max_length=99, blank=True,null=True)
    per_zip = models.CharField(verbose_name='per_zip', max_length=99, blank=True,null=True)

class family_background(models.Model):
    authUser = models.OneToOneField(User, on_delete=models.CASCADE, verbose_name='authUser' ,blank=True,null=True)
    spouse_surname = models.CharField(verbose_name='spouse_surname', max_length=99 ,blank=True,null=True)
    spouse_extension = models.CharField(verbose_name='spouse_extension', max_length=99 ,blank=True,null=True)
    spouse_firstname = models.CharField(verbose_name='spouse_firstname', max_length=99 ,blank=True,null=True)
    spouse_middlename = models.CharField(verbose_name='spouse_middlename', max_length=99 ,blank=True,null=True)
    occupation = models.CharField(verbose_name='occupation', max_length=99 ,blank=True,null=True)
    employee_name = models.CharField(verbose_name='employee_name', max_length=99 ,blank=True,null=True)
    business_address = models.CharField(verbose_name='business_address', max_length=99 ,blank=True,null=True)
    family_telno = models.CharField(verbose_name='family_telno', max_length=99 ,blank=True,null=True)
    father_firstname = models.CharField(verbose_name='father_firstname', max_length=99 ,blank=True,null=True)
    father_middlename = models.CharField(verbose_name='father_middlename', max_length=99 ,blank=True,null=True)
    father_surname = models.CharField(verbose_name='father_surname', max_length=99 ,blank=True,null=True)
    father_extension = models.CharField(verbose_name='father_extension', max_length=99 ,blank=True,null=True)
    mother_firstname = models.CharField(verbose_name='mother_firstname', max_length=99 ,blank=True,null=True)
    mother_middlename = models.CharField(verbose_name='mother_middlename', max_length=99 ,blank=True,null=True)
    mother_surname = models.CharField(verbose_name='mother_surname', max_length=99 ,blank=True,null=True)

    child1 = models.CharField(verbose_name='child1', max_length=99 ,blank=True,null=True)
    child2 = models.CharField(verbose_name='child2', max_length=99 ,blank=True,null=True)
    child3 = models.CharField(verbose_name='child3', max_length=99 ,blank=True,null=True)
    child4 = models.CharField(verbose_name='child4', max_length=99 ,blank=True,null=True)
    child5 = models.CharField(verbose_name='child5', max_length=99 ,blank=True,null=True)
    child6 = models.CharField(verbose_name='child6', max_length=99 ,blank=True,null=True)
    child7 = models.CharField(verbose_name='child7', max_length=99 ,blank=True,null=True)
    child8 = models.CharField(verbose_name='child8', max_length=99 ,blank=True,null=True)
    child9 = models.CharField(verbose_name='child9', max_length=99 ,blank=True,null=True)
    child10 = models.CharField(verbose_name='child10', max_length=99 ,blank=True,null=True)
    
    date_birth1 = models.DateField(verbose_name='date_birth1',blank=True,null=True,default=None)
    date_birth3 = models.DateField(verbose_name='date_birth3',blank=True,null=True,default=None)
    date_birth2 = models.DateField(verbose_name='date_birth2',blank=True,null=True,default=None)
    date_birth4 = models.DateField(verbose_name='date_birth4',blank=True,null=True,default=None)
    date_birth5 = models.DateField(verbose_name='date_birth5',blank=True,null=True,default=None)
    date_birth6 = models.DateField(verbose_name='date_birth6',blank=True,null=True,default=None)
    date_birth7 = models.DateField(verbose_name='date_birth7',blank=True,null=True,default=None)
    date_birth8 = models.DateField(verbose_name='date_birth8',blank=True,null=True,default=None)
    date_birth9 = models.DateField(verbose_name='date_birth9',blank=True,null=True,default=None)
    date_birth10 = models.DateField(verbose_name='date_birth10',blank=True,null=True,default=None)

class educational_background(models.Model):
    authUser = models.OneToOneField(User, on_delete=models.CASCADE, verbose_name='authUser' ,blank=True,null=True)
    elem_school = models.CharField(verbose_name='elem_school', max_length=99 ,blank=True,null=True)
    elem_course = models.CharField(verbose_name='elem_course', max_length=99 ,blank=True,null=True)
    elem_attendance_to = models.CharField(verbose_name='elem_attendance_to', max_length=99 ,blank=True,null=True)
    elem_attendance_from = models.CharField(verbose_name='elem_attendance_from', max_length=99 ,blank=True,null=True)
    elem_units = models.CharField(verbose_name='elem_units', max_length=99 ,blank=True,null=True)
    elem_grad = models.CharField(verbose_name='elem_grad', max_length=99 ,blank=True,null=True)
    elem_honors = models.CharField(verbose_name='elem_honors', max_length=99 ,blank=True,null=True)

    secondary_school = models.CharField(verbose_name='secondary_school', max_length=99 ,blank=True,null=True)
    secondary_course = models.CharField(verbose_name='secondary_course', max_length=99 ,blank=True,null=True)
    secondary_attendance_to = models.CharField(verbose_name='secondary_attendance_to', max_length=99 ,blank=True,null=True)
    secondary_attendance_from = models.CharField(verbose_name='secondary_attendance_from', max_length=99 ,blank=True,null=True)
    secondary_units = models.CharField(verbose_name='secondary_units', max_length=99 ,blank=True,null=True)
    secondary_grad = models.CharField(verbose_name='secondary_grad', max_length=99 ,blank=True,null=True)
    secondary_honors = models.CharField(verbose_name='secondary_honors', max_length=99 ,blank=True,null=True)

    vocational_school = models.CharField(verbose_name='vocational_school', max_length=99 ,blank=True,null=True)
    vocational_course = models.CharField(verbose_name='vocational_course', max_length=99 ,blank=True,null=True)
    vocational_attendance_to = models.CharField(verbose_name='vocational_attendance_to', max_length=99 ,blank=True,null=True)
    vocational_attendance_from = models.CharField(verbose_name='vocational_attendance_from', max_length=99 ,blank=True,null=True)
    vocational_units = models.CharField(verbose_name='vocational_units', max_length=99 ,blank=True,null=True)
    vocational_grad = models.CharField(verbose_name='vocational_grad', max_length=99 ,blank=True,null=True)
    vocational_honors = models.CharField(verbose_name='vocational_honors', max_length=99 ,blank=True,null=True)
    
    college_school = models.CharField(verbose_name='college_school', max_length=99 ,blank=True,null=True)
    college_course = models.CharField(verbose_name='college_course', max_length=99 ,blank=True,null=True)
    college_attendance_to = models.CharField(verbose_name='college_attendance_to', max_length=99 ,blank=True,null=True)
    college_attendance_from = models.CharField(verbose_name='college_attendance_from', max_length=99 ,blank=True,null=True)
    college_units = models.CharField(verbose_name='college_units', max_length=99 ,blank=True,null=True)
    college_grad = models.CharField(verbose_name='college_grad', max_length=99 ,blank=True,null=True)
    college_honors = models.CharField(verbose_name='college_honors', max_length=99 ,blank=True,null=True)

    grad_school = models.CharField(verbose_name='grad_school', max_length=99 ,blank=True,null=True)
    grad_course = models.CharField(verbose_name='grad_course', max_length=99 ,blank=True,null=True)
    grad_attendance_to = models.CharField(verbose_name='grad_attendance_to', max_length=99 ,blank=True,null=True)
    grad_attendance_from = models.CharField(verbose_name='grad_attendance_from', max_length=99 ,blank=True,null=True)
    grad_units = models.CharField(verbose_name='grad_units', max_length=99 ,blank=True,null=True)
    grad_grad = models.CharField(verbose_name='grad_grad', max_length=99 ,blank=True,null=True)
    grad_honors = models.CharField(verbose_name='grad_honors', max_length=99 ,blank=True,null=True)

class civil_service_eligibility(models.Model):
    authUser = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='authUser' ,blank=True,null=True)
    eligibility = models.CharField(verbose_name='eligibility', max_length=99,blank=True,null=True)
    rating = models.CharField(verbose_name='rating', max_length=99,blank=True,null=True)
    exam_date = models.DateTimeField(verbose_name='exam_date',blank=True,null=True)
    exam_place = models.CharField(verbose_name='exam_place', max_length=99,blank=True,null=True)
    license_number = models.CharField(verbose_name='license_number', max_length=99,blank=True,null=True)
    license_validity_date = models.DateTimeField(verbose_name='license_validity_date', max_length=99,blank=True,null=True)

class work_experience(models.Model):
    authUser = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='authUser' ,blank=True,null=True)
    date_from = models.DateTimeField(verbose_name='date_from', max_length=99)
    date_to = models.DateTimeField(verbose_name='date_to', max_length=99)
    position = models.CharField(verbose_name='position', max_length=99)
    department = models.CharField(verbose_name='department', max_length=99)
    monthly_salary = models.CharField(verbose_name='monthly_salary', max_length=99)
    salary_grade = models.CharField(verbose_name='salary_grade', max_length=99)
    status = models.CharField(verbose_name='status', max_length=99)
    gov_service = models.CharField(verbose_name='gov_service', max_length=99)

class voluntary_work(models.Model):
    authUser = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='authUser' ,blank=True,null=True)
    org_info = models.CharField(verbose_name='org_info', max_length=99)
    date_from = models.DateTimeField(verbose_name='date_from', max_length=99)
    date_to = models.DateTimeField(verbose_name='date_to', max_length=99)
    work_hours = models.CharField(verbose_name='work_hours', max_length=99)
    position = models.CharField(verbose_name='position', max_length=99)

class learning_development(models.Model):
    authUser = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='authUser' ,blank=True,null=True)
    title = models.CharField(verbose_name='title', max_length=99)
    date_of_attendance_from = models.DateTimeField(verbose_name='date_of_attendance_from', max_length=99)
    date_of_attendance_to = models.DateTimeField(verbose_name='date_of_attendance_to', max_length=99)
    work_hours = models.CharField(verbose_name='work_hours', max_length=99)
    type_of_ld = models.CharField(verbose_name='type_of_ld', max_length=99)
    conducted = models.CharField(verbose_name='conducted', max_length=99)

class other_info(models.Model):
    authUser = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='authUser' ,blank=True,null=True)
    skills_hobbies = models.CharField(verbose_name='skills_hobbies', max_length=99)
    non_acad_recognition = models.CharField(verbose_name='non_acad_recognition', max_length=99)
    membership = models.CharField(verbose_name='membership', max_length=99)

class references(models.Model):
    authUser = models.OneToOneField(User, on_delete=models.CASCADE, verbose_name='authUser' ,blank=True,null=True)
    name1 = models.CharField(verbose_name='name1', max_length=99 ,blank=True,null=True)
    name2 = models.CharField(verbose_name='name2', max_length=99 ,blank=True,null=True)
    name3 = models.CharField(verbose_name='name3', max_length=99 ,blank=True,null=True)
    address1 = models.CharField(verbose_name='address1', max_length=99 ,blank=True,null=True)
    address2 = models.CharField(verbose_name='address2', max_length=99 ,blank=True,null=True)
    address3 = models.CharField(verbose_name='address3', max_length=99 ,blank=True,null=True)
    telno1 = models.CharField(verbose_name='telno1', max_length=99 ,blank=True,null=True)
    telno2 = models.CharField(verbose_name='telno2', max_length=99 ,blank=True,null=True)
    telno3 = models.CharField(verbose_name='telno3', max_length=99 ,blank=True,null=True)
    gov_id = models.CharField(verbose_name='gov_id', max_length=99 ,blank=True,null=True)
    license_id = models.CharField(verbose_name='license_id', max_length=99 ,blank=True,null=True)
    date = models.DateField(verbose_name='date',blank=True,null=True)


class miscellaneousinfo(models.Model):
    authUser = models.OneToOneField(User, on_delete=models.CASCADE, verbose_name='authUser' ,blank=True,null=True)    
    
    third_degree = models.CharField(verbose_name='third_degree', max_length=99 ,blank=True,null=True)
    third_degree_specify = models.CharField(verbose_name='third_degree_specify', max_length=99 ,blank=True,null=True)
    fourth_degree = models.CharField(verbose_name='fourth_degree', max_length=99 ,blank=True,null=True)
    fourth_degree_specify = models.CharField(verbose_name='fourth_degree_specify', max_length=99 ,blank=True,null=True)
    guilty = models.CharField(verbose_name='guilty', max_length=99 ,blank=True,null=True)
    guilty_specify = models.CharField(verbose_name='guilty_specify', max_length=99 ,blank=True,null=True) 
    criminally = models.CharField(verbose_name='criminally', max_length=99 ,blank=True,null=True)
    criminally_specify = models.CharField(verbose_name='criminally_specify', max_length=99 ,blank=True,null=True) 
    date = models.DateField(verbose_name='date',blank=True,null=True)

    convicted = models.CharField(verbose_name='convicted', max_length=99 ,blank=True,null=True)
    convicted_specify = models.CharField(verbose_name='convicted_specify', max_length=99 ,blank=True,null=True) 
    separated_service = models.CharField(verbose_name='separated_service', max_length=99 ,blank=True,null=True)
    separated_service_specify = models.CharField(verbose_name='separated_service_specify', max_length=99 ,blank=True,null=True)
    candidate = models.CharField(verbose_name='candidate', max_length=99 ,blank=True,null=True)
    candidate_specify = models.CharField(verbose_name='candidate_specify', max_length=99 ,blank=True,null=True)     
    resigned = models.CharField(verbose_name='resigned', max_length=99 ,blank=True,null=True)
    resigned_specify = models.CharField(verbose_name='resigned_specify', max_length=99 ,blank=True,null=True) 
    immigrant = models.CharField(verbose_name='immigrant', max_length=99 ,blank=True,null=True)
    immigrant_specify = models.CharField(verbose_name='immigrant_specify', max_length=99 ,blank=True,null=True)  

    indigenous = models.CharField(verbose_name='indigenous', max_length=99 ,blank=True,null=True)
    indig_specify = models.CharField(verbose_name='indig_specify', max_length=99 ,blank=True,null=True)
    disability = models.CharField(verbose_name='disability', max_length=99 ,blank=True,null=True)
    disab_specify = models.CharField(verbose_name='disab_specify', max_length=99 ,blank=True,null=True)
    solo_parent = models.CharField(verbose_name='solo_parent', max_length=99 ,blank=True,null=True)
    solo_specify = models.CharField(verbose_name='solo_specify', max_length=99 ,blank=True,null=True)
